services:
    web:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        links:
            - php

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/var/www/html

    test:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        command: vendor/bin/phpunit --testdox /app/tests/
        volumes:
            - .:/var/www/html

    # composer:
    #     image: composer
    #     volumes:
    #         - .:/app
    #     command: install
